# Generated by Django 2.0.4 on 2018-06-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankserverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='funcionario_cadastrou',
            field=models.CharField(max_length=45),
        ),
    ]
