# Generated by Django 2.0.4 on 2018-06-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankserverapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cadastroDatetime',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
