# Generated by Django 2.0.4 on 2018-06-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankserverapp', '0002_auto_20180624_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='agencia',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='adm_cadastrou',
            field=models.CharField(max_length=50),
        ),
    ]
