# Generated by Django 2.0.4 on 2018-06-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankserverapp', '0002_auto_20180608_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='origem_funcionario_id',
            field=models.IntegerField(default=99999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
