# Generated by Django 2.0.4 on 2018-06-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankserverapp', '0003_auto_20180624_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
    ]
