# Generated by Django 2.0.4 on 2018-06-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankserverapp', '0004_remove_funcionario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(),
        ),
    ]
